// gleann plugin for OpenCode
// Auto-generated by: gleann install --platform opencode
// Docs: https://opencode.ai/docs/plugins/
import fs from "fs";
import { spawnSync } from "child_process";

function getGleannContext() {
  const parts = [];

  // ── Knowledge graph summary ─────────────────────────────────────────────
  if (fs.existsSync("GRAPH_REPORT.md")) {
    const content = fs.readFileSync("GRAPH_REPORT.md", "utf8");
    // First 2000 chars covers the summary + god nodes section
    parts.push("## gleann Knowledge Graph\n\n" + content.slice(0, 2000));
  } else {
    parts.push(
      "## gleann\nNo GRAPH_REPORT.md found. " +
      "Run: gleann graph report --index <name>  to generate it."
    );
  }

  // ── Long-term memory ────────────────────────────────────────────────────
  try {
    const r = spawnSync(
      "gleann",
      ["memory", "list", "--json"],
      { encoding: "utf8", timeout: 3000 }
    );
    if (r.status === 0 && r.stdout.trim()) {
      const blocks = JSON.parse(r.stdout);
      if (blocks && blocks.length > 0) {
        const lines = blocks
          .map((b) => "- [" + b.tier + "] " + b.content)
          .join("\n");
        parts.push(
          "## gleann Memory (" + blocks.length + " blocks)\n\n" + lines
        );
      }
    }
  } catch (_) { /* gleann not installed or memory empty — silently skip */ }

  return parts.join("\n\n");
}

// GleannPlugin hooks into OpenCode's event system.
// See: https://opencode.ai/docs/plugins/#events
export const GleannPlugin = async ({ project, client, $, directory, worktree }) => {
  return {
    // Inject gleann context whenever the session is compacted.
    // This keeps the LLM aware of the knowledge graph and persistent memory
    // even after long sessions where the context window is rolled over.
    "experimental.session.compacting": async (input, output) => {
      const ctx = getGleannContext();
      if (ctx) {
        output.context.push(ctx);
      }
    },
  };
};
